---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.5.0-jdk-8

inputs:
  - name: dp-performance-reporter

outputs:
  - name: build

run:
  path: dp-performance-reporter/ci/scripts/build.sh
